# Generated by Django 5.0.6 on 2024-06-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userprofile_isverified_userprofile_teststring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='testString',
            field=models.TextField(default='TEST STRING THIS'),
        ),
    ]
