# Generated by Django 4.0.5 on 2024-06-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_field',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='new_field',
        ),
    ]
