# Generated by Django 4.0.5 on 2024-06-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_userprofile_teststring'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='governmentId',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proofOfIncome',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
