# Generated by Django 4.0.5 on 2024-06-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_userprofile_governmentid_userprofile_proofofincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='governmentId',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proofOfIncome',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
