# Generated by Django 4.0.5 on 2024-06-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_alter_cashassistance_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashassistance',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='cashassistance',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Decline', 'Decline'), ('Pending', 'Pending')], default='Pending', max_length=256),
        ),
    ]
