# Generated by Django 4.0.5 on 2024-06-05 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0011_alter_userprofile_governmentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('proof_of_residency', models.FileField(null=True, upload_to='documents/')),
                ('household_member_count', models.IntegerField(null=True)),
                ('special_categories', models.JSONField(null=True)),
                ('employment_status', models.TextField(null=True)),
                ('monthly_income', models.BigIntegerField(null=True)),
                ('government_aid', models.BooleanField(null=True)),
                ('income_verification', models.FileField(null=True, upload_to='documents/')),
                ('reason', models.TextField(null=True)),
                ('other_proof', models.FileField(null=True, upload_to='documents/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userprofile')),
            ],
        ),
    ]
