# Generated by Django 4.0.5 on 2024-06-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashassistance',
            name='reason',
            field=models.JSONField(null=True),
        ),
    ]
